### ISSUE TITLE
Unhandled exception. System.NotSupportedException: GenerateCrudServices.DbFactory is not configured

### ISSUE THREAD

**Issue by ganeshan** [NetCoreApps/Chinook#1]
Here is my setup:
`x --version` 
output:
`Version: 8.0.1
ServiceStack: 8.13
Framework: .NET 8.0.2
OS: Unix 11.7.10`
I am running on an Intel Mac.
I created the App using:
`x new web Chinook`
`cd Chinook`
`x mix autocrudgen sqlite chinook.sqlite`
In Chinook/Configure.Db.cs
.ConfigureServices((context, services) => {
            services.AddSingleton<IDbConnectionFactory>(new OrmLiteConnectionFactory(
                context.Configuration.GetConnectionString("DefaultConnection")
                ?? "chinook.sqlite",
                SqliteDialect.Provider));
        })
 When I run:
 `dotnet run`
 I get:
Unhandled exception. System.NotSupportedException: GenerateCrudServices.DbFactory is not configured
   at ServiceStack.GenerateCrudServices.GetMissingTypesToCreate(Dictionary`2& typesMap) in /home/runner/work/ServiceStack/ServiceStack/ServiceStack/src/ServiceStack.Server/GenerateCrudServices.cs:line 767
   at ServiceStack.GenerateCrudServices.GenerateMissingServices(AutoQueryFeature feature, HashSet`1 requestTypes) in /home/runner/work/ServiceStack/ServiceStack/ServiceStack/src/ServiceStack.Server/GenerateCrudServices.cs:line 224
   at ServiceStack.AutoQueryFeature.AfterConfigure(IServiceCollection services) in /home/runner/work/ServiceStack/ServiceStack/ServiceStack/src/ServiceStack.Server/AutoQueryFeature.cs:line 191
   at ServiceStack.ServiceStackServicesOptions.ConfigurePlugins(IServiceCollection services) in /home/runner/work/ServiceStack/ServiceStack/ServiceStack/src/ServiceStack/AppHostBase.Options.cs:line 37
   at ServiceStack.NetCoreAppHostExtensions.AddServiceStack(IServiceCollection services, IEnumerable`1 serviceAssemblies, Action`1 configure) in /home/runner/work/ServiceStack/ServiceStack/ServiceStack/src/ServiceStack/AppHostBase.NetCore.cs:line 645
   at ServiceStack.NetCoreAppHostExtensions.AddServiceStack(IServiceCollection services, Assembly serviceAssembly, Action`1 configure) in /home/runner/work/ServiceStack/ServiceStack/ServiceStack/src/ServiceStack/AppHostBase.NetCore.cs:line 632
   at Program.<Main>$(String[] args) in /Users/xxxxx/Chinook/Chinook/Program.cs:line 6

**Comment by mythz** [comment]
When using Endpoint Routing the DbFactory needs to be configured on `GenerateCrudServices` as any dynamically created services need to be registered in ASP .NET Core IOC before the AppHost is initialized, e.g:

```csharp
var dbFactory = new OrmLiteConnectionFactory(
    context.Configuration.GetConnectionString("DefaultConnection")
    ?? "App_Data/chinook.sqlite",
    SqliteDialect.Provider);
    
services.AddSingleton<IDbConnectionFactory>(dbFactory);
    
services.AddPlugin(new AutoQueryFeature {
    MaxLimit = 1000,
    IncludeTotal = true,
    // Enable AutoGen to generate APIs and Models for RDBMS:
    GenerateCrudServices = new GenerateCrudServices {
        DbFactory = dbFactory, 
        AutoRegister = true,
        AddDataContractAttributes = false,
    }
});
```
